name: Feature Form
description: File a feature issue.
title: "feat/: new funcionality"
labels: ["enhancenment"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature form!
  - type: textarea
    id: what-description
    attributes:
      label: Description
      description: High-level description of a software feature
      placeholder: Tell us what you want!
      value: "We want to have "
    validations:
      required: true
  - type: dropdown
    id: estimation
    attributes:
      label: Estimation
      description: What Estimation points?
      options:
        - 1pt
        - 2pts
        - 3pts
        - 5pts
        - 8pts
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Feature
        - Epic
        - Safari
        - Microsoft Edge
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: |
        Define the conditions that must be met for this feature to be accepted.
        Example:
        - [ ] A toggle is visible in settings
        - [ ] Toggling switches the theme
        - [ ] Theme preference persists across sessions
      placeholder: |
        - [ ] A toggle is visible in settings
        - [ ] Toggling switches the theme
        - [ ] Theme preference persists across sessions
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Definition of Ready
      description: it can be considered ready for development [Definition of Ready](https://microsoft.github.io/code-with-engineering-playbook/agile-development/team-agreements/definition-of-ready). 
      options:
        - label: I agree to acceptance the Definition of Ready issue's
          required: true