name: Feature Request
description: Submit a request for a new feature or improvement.
title: "[Feature]: "
labels: [enhancement]
assignees:
  - your-github-username  # Optional: remove or replace
body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Feature Request Form
        Please fill out the following fields to help us understand your request.

  - type: input
    id: feature-summary
    attributes:
      label: Feature Summary
      placeholder: "e.g. Add dark mode toggle in user settings"
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem are you trying to solve with this feature?
      placeholder: |
        e.g. Users are experiencing eye strain using the current bright theme at night.
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: |
        Define the conditions that must be met for the feature to be considered complete.
        Use checkboxes to list each criterion.
      placeholder: |
        - [ ] A dark mode toggle is visible in settings
        - [ ] Dark mode applies instantly without refresh
        - [ ] Preference is saved and persists across sessions
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce (if applicable)
      description: |
        If this feature addresses a recurring problem, include the steps to replicate the issue.
      placeholder: |
        1. Go to settings
        2. Try to find theme options
        3. No toggle available for dark mode
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent or important is this feature?
      options:
        - High (critical to user needs or functionality)
        - Medium (important but not urgent)
        - Low (nice to have)
    validations:
      required: true

  - type: textarea
    id: business-value
    attributes:
      label: Business Value / User Impact
      description: |
        Describe the value this feature brings to the project or users.
      placeholder: |
        Improves accessibility for users working in low-light environments.
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Mockups
      description: |
        Add any visual references that may help understand the request.
      placeholder: "You can upload images by dragging and dropping them here."
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Any other information, links, dependencies, or blockers to consider?
    validations:
      required: false
