name: Solicitud de Funcionalidad
description: Envía una propuesta para una nueva funcionalidad o mejora.
title: "[Funcionalidad]: "
labels: [enhancement]
assignees: []  # Opcional: puedes asignar por defecto a miembros del equipo
body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Formulario de Solicitud de Funcionalidad
        Ayúdanos a entender y priorizar tu solicitud completando el siguiente formulario.

  - type: input
    id: feature-summary
    attributes:
      label: 📌 Resumen de la Funcionalidad
      placeholder: "Ej: Añadir modo oscuro en la configuración de usuario"
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: 🔍 Problema o Necesidad
      description: ¿Qué problema estás tratando de resolver con esta funcionalidad?
      placeholder: |
        Ej: Los usuarios que trabajan de noche encuentran la interfaz muy brillante, causando molestias visuales.
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Criterios de Aceptación
      description: |
        Lista las condiciones que deben cumplirse para que la funcionalidad se considere completada. Usa casillas de verificación.
      placeholder: |
        - [ ] Hay un interruptor visible en la configuración
        - [ ] Cambiar el interruptor activa el modo oscuro inmediatamente
        - [ ] La preferencia se guarda y se mantiene entre sesiones
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🪜 Pasos para Reproducir (si aplica)
      description: |
        Si esta funcionalidad mejora o corrige un comportamiento existente, incluye los pasos para reproducir el problema.
      placeholder: |
        1. Ir a configuración
        2. Observar que no existe una opción para activar el modo oscuro
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: 🎯 Prioridad
      description: ¿Qué tan importante es esta funcionalidad para los usuarios o el negocio?
      options:
        - Alta (esencial para MVP o flujos críticos)
        - Media (valiosa pero no urgente)
        - Baja (interesante, pero no imprescindible)
    validations:
      required: true

  - type: dropdown
    id: estimation
    attributes:
      label: 🧮 Estimación (Escala Fibonacci)
      description: Estima el esfuerzo o complejidad utilizando la escala de puntos de historia.
      options:
        - 0 (trivial)
        - 1 (muy pequeña)
        - 2 (pequeña)
        - 3 (media)
        - 5 (moderadamente compleja)
        - 8 (compleja)
        - 13 (muy compleja)
        - 21 (nivel épico)
        - ∞ (demasiado grande, necesita dividirse)
        - ? (incierta)
    validations:
      required: true

  - type: textarea
    id: business-value
    attributes:
      label: 💡 Valor para el Negocio / Impacto en el Usuario
      description: ¿Qué valor aporta esta funcionalidad a los usuarios o al proyecto?
      placeholder: |
        Mejora la accesibilidad para usuarios que trabajan en entornos con poca luz y reduce la fatiga visual.
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: 🖼️ Capturas de Pantalla / Mockups
      description: Añade referencias visuales que ayuden a entender mejor la solicitud.
      placeholder: "Puedes subir imágenes arrastrándolas aquí o pegar enlaces a diseños."
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 📎 Contexto Adicional
      description: ¿Hay información relevante, bloqueos, vínculos a issues relacionados u otros detalles que debamos considerar?
    validations:
      required: false

  - type: checkboxes
    id: definition-of-ready
    attributes:
      label: 🧾 Confirmación de la Definición de Listo
      description: |
        Por favor, confirma que esta solicitud cumple con nuestra [Definición de Listo](https://microsoft.github.io/code-with-engineering-playbook/agile-development/team-agreements/definition-of-ready/).
      options:
        - label: Confirmo que esta funcionalidad cumple con la Definición de Listo y contiene suficiente detalle para ser estimada e implementada.
          required: true
