name: Feature Form
description: File a feature issue.
title: "feat/: new funcionality"
labels: ["enhancenment"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature form!
  - type: textarea
    id: what-description
    attributes:
      label: Description
      description: High-level description of a software feature
      placeholder: Tell us what you want!
      value: "We want to have "
    validations:
      required: true
  - type: dropdown
    id: estimation
    attributes:
      label: Estimation
      description: What Estimation points?
      options:
        - 1
        - 2
        - 3
        - 5
        - 8
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Cirteria
      description: Explain steps to verify the feature is working.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Definition of Ready
      description: it can be considered ready for development [Definition of Ready](https://microsoft.github.io/code-with-engineering-playbook/agile-development/team-agreements/definition-of-ready). 
      options:
        - label: I agree to acceptance the Definition of Ready issue's
          required: true